# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Yes, there is a difference in the data type of the 'list_' and 'array_list' variables. The 'list_' variable is a Python list containing string elements, while the 'array_list' variable is a NumPy array. We can check the data types of these variables using the type() function.

In [7]:
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [8]:
list_ = ['1', '2', '3', '4', '5']
list_

['1', '2', '3', '4', '5']

In [43]:
array_list = np.array(list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [44]:
for i in list_:
    print("Data type of element in 'list_':", type(i))

Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>


In [45]:
for i in array_list:
    print("Data type of element in 'array_list':", type(i))

Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [46]:
list_

['1', '2', '3', '4', '5']

In [47]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [48]:
for i in list_:
    print("Data type of element in 'list_':", type(i))

Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>
Data type of element in 'list_': <class 'str'>


In [49]:
for k in array_list:
    print("Data type of element in 'array_list':", type(k))

Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>
Data type of element in 'array_list': <class 'numpy.str_'>


In [50]:
array_list2 = np.array(object = list_, dtype = int)

In [33]:
array_list2

array([1, 2, 3, 4, 5])

In [34]:
for i in array_list:
    print("Data type of element in 'array_list':", type(i))

Data type of element in 'array_list': <class 'numpy.int32'>
Data type of element in 'array_list': <class 'numpy.int32'>
Data type of element in 'array_list': <class 'numpy.int32'>
Data type of element in 'array_list': <class 'numpy.int32'>
Data type of element in 'array_list': <class 'numpy.int32'>


# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [51]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [56]:
shape =num_array.shape
shape

(2, 3)

In [57]:
size =num_array.size
size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [59]:
mm=np.zeros((3,3))
mm

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [60]:
ii=np.eye(5)
ii

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])